{{- if not .Values.hub.existingSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: hub-secret
  annotations:
    {{- if ne (not .Values.proxy.secretToken) (not .Values.auth.state.cryptoKey) }}
    {{- /* Should always provide both secretToken and cryptoKey, or both no secretToken and no cryptoKey */ -}}
    {{- fail "[Fail] Should always provide both .Values.proxy.secretToken and .Values.auth.state.cryptoKey or both no .Values.proxy.secretToken and no .Values.auth.state.cryptoKey" }}
    {{- end }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- if and (not .Values.proxy.secretToken) (not .Values.auth.state.cryptoKey)  }}
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
    {{- end }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- $values := merge dict .Values }}
  {{- /* preserve behavior of deprecated hub.extraConfigMap */}}
  {{- $_ := set $values "custom" (merge dict $values.custom .Values.hub.extraConfigMap) }}
  {{- /* passthrough subset of Chart / Release */}}
  {{- $_ := set $values "Chart" (dict "Name" .Chart.Name "Version" .Chart.Version) }}
  {{- $_ := set $values "Release" (pick .Release "Name" "Namespace" "Service") }}
  values.yaml: {{ $values | toYaml | b64enc | quote }}

  # Used to mount CONFIGPROXY_AUTH_TOKEN on hub/proxy pods for mutual trust
  {{- if .Values.proxy.secretToken }}
  proxy.token: {{ .Values.proxy.secretToken | b64enc | quote }}
  {{- else }}
  proxy.token: {{ printf "%x" (randAlphaNum 32) | b64enc | quote }}
  {{- end }}

  {{- with .Values.hub.db.password }}
  # Used to mount MYSQL_PWD or PGPASSWORD on hub pod
  hub.db.password: {{ . | b64enc | quote }}
  {{- end }}

  {{- range $key, $service := .Values.hub.services }}
  {{- if $service.apiToken }}
  # Potentially used to mount on an external service in the k8s cluster
  services.token.{{$key}}: {{ $service.apiToken | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- if .Values.auth.state.enabled }}
  # Used to mount JUPYTERHUB_CRYPT_KEY on hub pod, used by authenticators
  {{- if .Values.auth.state.cryptoKey }}
  auth.state.crypto-key: {{ .Values.auth.state.cryptoKey | b64enc | quote }}
  {{- else }}
  auth.state.crypto-key: {{ printf "%x" (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
